from tkinter import SEPARATOR
import pygame

# pygame properties
FRAME_RATE = 60
DISPLAY_WIDTH = 800
DISPLAY_HEIGHT = 600
BACKGROUND_COLOR = (100, 149, 237)
BORDER_RADIUS = 75
BOUNDARY_FORCE = 1
CLOCK = pygame.time.Clock()
DELTATIME = CLOCK.tick(60) * .001 * FRAME_RATE

# agent properties
VECTOR_LINE_LENGTH = 25
AGENT_WIDTH = 16
AGENT_HEIGHT = 32

#player properties
PLAYER_SIZE = 10
PLAYER_SPD = 1.5
PLAYER_COLOR = (255, 255, 0)
PLAYER_XPOS = DISPLAY_WIDTH / 2
PLAYER_YPOS = DISPLAY_HEIGHT / 2
PLAYER_TO_SHEEP_FORCE = 1
PLAYER_TURN_SPEED = 0.2

# enemy properties
ENEMY_SIZE = 10
ENEMY_SPD = 1
ENEMY_COLOR = (0, 255, 0)
MAX_ENEMIES = 10
FLEE_RANGE = 200
ENEMY_FLEE_FORCE = 1
ENEMY_WANDER_FORCE = 1
ENEMY_TURN_SPEED = 0.1
SHEEP_NEIGHBOR_RADIUS = 300
ALIGNMENT_WEIGHT = 1
SEPARATION_WEIGHT = 1
COHESION_WEIGHT = 1

#debug
ENABLE_DOG = True
ENABLE_ALIGNMENT = True
ENABLE_COHESION = True
ENABLE_SEPARATION = True
ENABLE_BOUNDARIES = True

DEBUGGING = True
DEBUG_LINE_WIDTH = 1
DEBUG_VELOCITY = DEBUGGING
DEBUG_BOUNDARIES = DEBUGGING
DEBUG_NEIGHBORS = DEBUGGING
DEBUG_DOG_INFLUENCE = DEBUGGING
DEBUG_BOUNDING_RECTS = DEBUGGING